---
# This is the main configuration file. It contains the build parameters
# for the currently supported releases.

release:
  main:
    version-tags:
      - 'edge'
    base-image:
      alpine: '3.23'
      static: '3.23'
      ubuntu: 'noble'
      debian: 'bookworm'
    addon:
      core:
        pandoc-crossref: 'v0.3.22b'
      latex:
        texlive: '2025'
      typst:
        typst: '0.14.0'
      extra:
        eisvogel: '3.3.0'
        python:
          - 'pandoc-codeblock-include==1.1.*'
          - 'pandoc-latex-environment==1.2.*'
          - 'pandoc-include==1.4.*'

  3.9:
    version-tags:
      - '3.9.0.0'
      - '3.9.0'
      - '3.9'
      - '3'
      - 'latest'
    base-image:
      alpine: '3.23.3'
      static: '3.23.3'
      ubuntu: 'noble'
      debian: 'bookworm'
    addon:
      core:
        pandoc-crossref: 'v0.3.22b'
      latex:
        texlive: '2025'
      typst:
        typst: '0.14.0'
      extra:
        eisvogel: '3.3.0'
        python:
          - 'pandoc-codeblock-include==1.1.*'
          - 'pandoc-latex-environment==1.2.*'
          - 'pandoc-include==1.4.*'

  3.8.3:
    version-tags:
      - '3.8.3'
      - '3.8'
    base-image:
      alpine: '3.23.0'
      static: '3.23.0'
      ubuntu: 'noble'
      debian: 'bookworm'
    addon:
      core:
        pandoc-crossref: 'v0.3.22b'
      latex:
        texlive: '2025'
      typst:
        typst: '0.14.0'
      extra:
        eisvogel: '3.3.0'
        python:
          - 'pandoc-codeblock-include==1.1.*'
          - 'pandoc-latex-environment==1.2.*'
          - 'pandoc-include==1.4.*'

  3.8.2.1:
    version-tags:
      - '3.8.2.1'
      - '3.8.2'
    base-image:
      alpine: '3.22.2'
      static: '3.22.2'
      ubuntu: 'noble'
      debian: 'bookworm'
    addon:
      latex:
        texlive: '2025'
      typst:
        typst: '0.13.1'
      extra:
        eisvogel: '3.2.0'
        python:
          - 'pandoc-codeblock-include==1.1.*'
          - 'pandoc-latex-environment==1.2.*'
          - 'pandoc-include==1.4.*'

  3.7.0.2:
    version-tags:
      - '3.7.0.2'
      - '3.7.0'
      - '3.7'
    base-image:
      alpine: '3.21.5'
      static: '3.21.5'
      ubuntu: 'noble'
    addon:
      latex:
        texlive: '2025'
      typst:
        typst: '0.12.0'
      extra:
        eisvogel: '3.2.0'
        python:
          - 'pandoc-codeblock-include==1.1.*'
          - 'pandoc-latex-environment==1.2.*'
          - 'pandoc-include==1.4.*'

  3.6.4:
    version-tags:
      - '3.6.4.0'
      - '3.6.4'
      - '3.6'
    base-image:
      alpine: '3.21.5'
      static: '3.21.5'
      ubuntu: 'noble'
    addon:
      latex:
        texlive: '2024'
      typst:
        typst: '0.12.0'
      extra:
        eisvogel: '3.2.0'
        python:
          - 'pandoc-codeblock-include==1.1.*'
          - 'pandoc-latex-environment==1.2.*'
          - 'pandoc-include==1.4.*'

  3.5:
    version-tags:
      - '3.5.0.0'
      - '3.5.0'
      - '3.5'
    base-image:
      alpine: '3.20.8'
      static: '3.20.8'
      ubuntu: 'noble'
    addon:
      latex:
        texlive: '2024'
      typst:
        typst: '0.11.1'
      extra:
        eisvogel: '3.0.0'
        python:
          - 'pandoc-codeblock-include==1.1.*'
          - 'pandoc-latex-environment==1.2.*'
          - 'pandoc-include==1.4.*'

  3.2.1:
    version-tags:
      - '3.2.1.0'
      - '3.2.1'
      - '3.2'
    base-image:
      alpine: '3.19.9'
      static: '3.19.9'
      ubuntu: 'noble'
    addon:
      latex:
        texlive: '2024'
      extra:
        eisvogel: '2.4.2'
        python:
          - 'pandoc-codeblock-include==1.1.*'
          - 'pandoc-latex-environment==1.2.*'
          - 'pandoc-include==1.4.*'

addon:
  core:
    hashes:
      pandoc-crossref:
        v0.3.22b:
          amd64: a521900745f7c1621b4104119f92dd4a9b4cc527f50157ef544ae1cb8435f9c1
          arm64: aaaeae858b73a4150cc91581b07e08fb6e383f476a04fd024bb03ef323b32c3e
  latex:
    texlive:
      current: 2025

  typst:
    hashes:
      0.14.0:
        amd64: 99816d2982de08d2b091bac56b59b2faa523a10e1378ad3cdd68e35b8eb74b3d
        arm64: 3ad461772773256021ff38a0db3acf85f3ecdb00b93606a32f8c5ae043f6c62b
      0.13.1:
        amd64: 7d214bfeffc2e585dc422d1a09d2b144969421281e8c7f5d784b65fc69b5673f
        arm64: 4f5b7ee6e57fb639019ee0f6bffcf940edad228ede6ff5269a9f05a1544ceed4
      0.12.0:
        amd64: 605130a770ebd59a4a579673079cb913a13e75985231657a71d6239a57539ec3
        arm64: e81ae98e6b12db5a36c2276e5a9890da48f7a339b92476dd22daf90de3699e11
      0.11.1:
        amd64: bb637d1d65634b2ee4b4e101d0b2d541bf3f1e03ac5f51f9619941e48dd28bd0
        arm64: 7f14f7fb37b26febffd13e683f90cdacddfde420d5fdc7f809228a78545c4b26
  extra: {}

variants:
  - name: minimal
    title: 'pandoc (minimal)'
    description: >-
      Minimal image for pandoc, the universal document converter.
    default-stack: static

  - name: core
    title: 'pandoc'
    description: >-
      Official pandoc image with image conversion tools and pandoc-crossref.
    default-stack: alpine

  - name: latex
    title: 'pandoc with LaTeX'
    description: >-
      Official pandoc image with pandoc, pandoc-crossref, and a minimal
      LaTeX installation.
    default-stack: alpine

  - name: extra
    title: 'pandoc with LaTeX and extras'
    description: >-
      Large pandoc image with many LaTeX extras, including popular fonts
      and the "Eisvogel" template.
    default-stack: alpine

  - name: typst
    title: 'pandoc with Typst'
    description: >-
      Document conversion with pandoc, pandoc-crossref, and Typst.
    default-stack: alpine
...

This document serves as the main configuration for the Dockerfiles
build system. It contains all tables and info required to generate
Dockerfiles and bake files.

The `pandock` Lua library contains the tools necessary to use
these configs and to build Dockerfiles. Each generated Dockerfile
is then added to the repository, so that the GitHub Actions build
system can access them to build the images.
